---
- name: Create Kubernetes Cluster using Kops
  hosts: localhost
  become: no
  vars:
    cluster_name: "k8scluster.k8s.local"        # MUST end with .k8s.local for gossip DNS
    state_store: "s3://my-k8s-bucket2200"       # Replace with your actual S3 bucket
    region: "us-east-1"                         # Your AWS region
    zones: "us-east-1a,us-east-1b"              # Availability zones
    node_count: 2
    node_size: "t2.medium"
    control_plane_size: "t2.medium"             # Updated from deprecated master-size

  tasks:
    - name: Export KOPS_STATE_STORE
      shell: "export KOPS_STATE_STORE={{ state_store }}"
      environment:
        KOPS_STATE_STORE: "{{ state_store }}"

    - name: Create kops cluster configuration using gossip DNS
      shell: |
        kops create cluster \
          --cloud=aws \
          --zones={{ zones }} \
          --name={{ cluster_name }} \
          --state={{ state_store }} \
          --node-count={{ node_count }} \
          --node-size={{ node_size }} \
          --control-plane-size={{ control_plane_size }} \
          --yes
      environment:
        KOPS_STATE_STORE: "{{ state_store }}"

    - name: Wait for cluster to be ready
      shell: |
        kops validate cluster --state={{ state_store }} --name {{ cluster_name }} --wait 10m
      register: validation
      retries: 10
      delay: 60
      until: validation.rc == 0

    - name: Display validation output
      debug:
        var: validation.stdout_lines

