---
- name: Delete Kubernetes Cluster using Kops
  hosts: localhost
  become: no
  vars:
    cluster_name: "k8scluster.example.com"    # Replace with your actual cluster domain
    state_store: "s3://your-kops-state-bucket"  # Replace with your actual S3 bucket

  tasks:
    - name: Delete the Kubernetes cluster
      shell: |
        kops delete cluster --name {{ cluster_name }} --state {{ state_store }} --yes
      environment:
        KOPS_STATE_STORE: "{{ state_store }}"

    - name: Print confirmation message
      debug:
        msg: "Cluster '{{ cluster_name }}' has been deleted from state store '{{ state_store }}'."
