---
- name: Install AWS CLI, Kops, and Kubectl on controller
  hosts: localhost
  become: yes
  tasks:

    - name: Install unzip and curl (Debian)
      apt:
        name:
          - unzip
          - curl
        state: present
      when: ansible_os_family == "Debian"

    - name: Check if AWS CLI is installed
      stat:
        path: /usr/local/bin/aws
      register: awscli_stat

    - name: Install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
      when: not awscli_stat.stat.exists

    - name: Check if kubectl is installed
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl_stat

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
      when: not kubectl_stat.stat.exists

    - name: Check if kops is installed
      stat:
        path: /usr/local/bin/kops
      register: kops_stat

    - name: Install kops
      shell: |
        curl -LO https://github.com/kubernetes/kops/releases/download/v1.28.0/kops-linux-amd64
        chmod +x kops-linux-amd64
        mv kops-linux-amd64 /usr/local/bin/kops
      when: not kops_stat.stat.exists

    - name: Verify installations
      shell: |
        aws --version
        kubectl version --client
        kops version
      register: tool_versions

    - name: Display installed tool versions
      debug:
        var: tool_versions.stdout_lines

